# Type constants
string POINT = point
string LINE = line
string POSE = pose
string POLY = poly
string ALL = all
string RESTRICTED = restricted
string FREESPACE = freespace
string NO_MARKER = no_selected_marker

string type
string source_id
string id
string description
geometry_msgs/Pose pose
geometry_msgs/Point position_source
geometry_msgs/Point position_target
string name
string action
bool is_line
string file_addr
bool is_written
