# Name of the template to be created
string station_name
# Region of interest for recording the template w.r.t to robot frame
geometry_msgs/PolygonStamped bounding_box
---
ipa_navigation_msgs/CompressedMapImage image
bool success
string message
