# Layer type of map
uint8 LAYER_TYPE_NDT_2D_GRID = 0
uint8 LAYER_TYPE_HMM_2D_GRID = 1
uint8 LAYER_TYPE_HR_OCC_2D_GRID = 2
uint8 LAYER_TYPE_NDT_3D_GRID_SLICE = 3
uint8 LAYER_TYPE_LW_HR_OCC_2D_GRID = 4

# Temporal type of map: static or long term
uint8 TEMPORAL_TYPE_LONG_TERM = 0
uint8 TEMPORAL_TYPE_STATIC = 1

uint8 layer_type
uint8 temporal_type
# Output resolution for HR_OCC_GRID, if output resolution is 0, the existing layer will be returned
float64 desired_hr_layer_resolution # unit: [m/cell]
# Slice for 3D NDT layer
uint8 slice
---
nav_msgs/OccupancyGrid map
bool success
string message
