string[] agent_id
string[] agent_type
geometry_msgs/PoseStamped[] start
geometry_msgs/PoseStamped[] goal

float32[] tolerance
float64 planning_time
int32 n_requests
---
nav_msgs/Path[] plan
float32[] cost
bool success
string message
